version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics

  stats-db:
    image: postgres:14-alpine
    container_name: my_stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICES_STATSSERVICE_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewm-db:
    image: postgres:14-alpine
    container_name: my_ewm-service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=root
