version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics

  stats-db:
    image: postgres:14-alpine
    container_name: statistics
    ports:
      - "6451:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm
    ports:
      - "6452:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=root